apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- imagestream.yaml
- buildconfig.yaml
- rbac-shinyproxy-sa.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- route.yaml
- external_route.yaml